### ISSUE TITLE
Ligand parameterization question

### ISSUE THREAD

**Issue by tantrev** [GHeinzelmann/BAT.py#15]
Hi there! This project is awesome - I'm just wondering if there's any easy way to drop-in ligand parameterization values from a package like [parameterize](https://github.com/Acellera/parameterize)?

**Comment by GHeinzelmann** [comment]
Hi Trevor, thanks! Sure, that is easy to do, as long as the parameters are in a format that tleap can read, usually .mol2 for the charges and .frcmod for the bonded and LJ parameters (when needed). What you need to do is, before running the code, create a equil/ff folder and put the parameter files in it. The name of the files should be the ligand three character code in lower case, for example, for a ligand called 89J the files should ne bames 89j.mol2 and 89j.frcmod. 

Let me see how that goes, you might have to also disable the GAFF option if you don't want to use GAFF parameters altogether, which is also easy to do, but let's try this first. Best,

Germano
