### ISSUE TITLE
Question on correct behaviour for the ligand only phase.

### ISSUE THREAD

**Issue by joe-bones** [GHeinzelmann/BAT.py#19]
Hi there!

I am modifying parts of this code for some specific runs and was just wondering as to the behaviour of specific parts with respect to the ligand only phases. I am just clarafying this as I wasn't certain after reading the corresponding paper and guide.

1. Are the ligand-only conformational dihedral restraints left on during the decoupling ligand-only phase in bulk solution, and the cost of these restraints calculated in a separate set of runs with the ligand fully coupled?
2. And if one is certain of a specific binding pose of a given ligand, do you think it would be viable to engage the ligand dihedral conformational as well as the translational restraints (the boresch type restraints) in a single set of simulations? 

Thanks for your time!

**Comment by GHeinzelmann** [comment]
Hello there! Sorry, just saw your comment! Below the answers to your enquiries:

1. Yes. The ligand is kept with the conformational restraints applied during the decoupling runs in the small box, which are are the f and w components of the DD method. Tha same goes for the bulk ligand in the e and v components of the SDR process. The c component has the ligand fully coupled in the small box, and here the conformational restraints are released until it is completely free (its final state).

2. I am not sure what you mean here, but I believe your idea is merging the l and t components, so all the ligand attachment components are performed using a single set of windows (a single component). If that is the case, the answer is yes, it is actually very easy to change that in the lib/setup.py file. I have also considered this approach, just haven't put it into practice yet.

Best,

Germano
