### ISSUE TITLE
Note: The following floating-point exceptions are signaling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

### ISSUE THREAD

**Issue by hfhfgo** [GHeinzelmann/BAT.py#22]
Dear Gheinzelmann,

Thanks for providing such convenient scripts 

Recently I was practicing the tutorial and using run-local.bash in equil folder, it shows "Note: The following floating-point exceptions are signaling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL". But the program can continue running, should I be really careful about this issue or just ignore it

Hope to receive your reply soon

Regards,
Andy

**Comment by GHeinzelmann** [comment]
Hi Andy. I think this message appears during the simulation when you use a pmemd.cuda version compiled with newer versions of the Fortran compiler. I believe it has do to with the hybrid single/double precision method used by the software, so there should be no reason for concern. Someone from AMBER could answer that more accurately, but I have seen this message as well and it did not interfere with the simulations.
