### ISSUE TITLE
File missing - Get last state from equilibrium simulations 

### ISSUE THREAD

**Issue by giangpth** [GHeinzelmann/BAT.py#24]
I encountered this problem during fe stage of the example when the program tried to copy the file  '../../../equil/pose0/md08.rst7' to the folder 'fe'. When I check the folder equil/pose0 there is no file named with this format. 
So, when was that (those) file created, did I miss any step?

**Comment by GHeinzelmann** [comment]
Hello. The .rst7 files are created when you run the equilibrium simulations using AMBER, either using the PBS file inside the folder to run in a server, or the run-local.bash script to run it locally.

**Comment by giangpth** [comment]
I could successfully run "python BAT.py -i input-dd.in -s equil" and also got the folder equil after running this. However during fe stage, when I run "python BAT.py -i input-dd.in -s fe" then I encountered this problem. 
So as I understood from your answer, after "python BAT.py -i input-dd.in -s equil" I need to run the simulation for each pose by run the script PBS-run inside each pose's folder. After this I can get the rst7 file and then I will be able to run fe stage normally? Am I getting this correctly? 
Thank you very much.

**Comment by GHeinzelmann** [comment]
Yes, that is correct, the simulation will create the .rst files you need, which contain the coordinates of the equilibrated system. Make sure you have the pmemd.cuda software from AMBER20 to run the simulations. In a similar fashion, you will also need to run several simulations for the fe stage before the analysis step.

**Comment by giangpth** [comment]
Hello, I realized that pmemd.cuda require the license of AMBER20 and it is not really affordable for me. Can you please recommend me any other alternative for this?

**Comment by GHeinzelmann** [comment]
Hello. Unfortunately at the moment BAT.py runs using only AMBER20, which requires a $ 500 licensing fee for non-profit purposes. Depending on your country of origin you can get a fee waiver, in which case there is no cost for you to get the pmemd.cuda software (https://ambermd.org/GetAmber.php).

I am planning to release the OpenMM version of BAT in the next few months, so soon you will be able to run the simulation using this open-source engine as well. Hope I could help.
