### ISSUE TITLE
Suggestion: SLURM support?

### ISSUE THREAD

**Issue by jaketanderson** [GHeinzelmann/BAT.py#28]
PBS is supported, so maybe some template scripts for the SLURM scheduler could be added. Like how PBS is set up, we would have individual scripts for each portion of the calculation (quil, rest, fe, etc.) and a user could manually (or automatically, using a custom script) execute each of those scripts to launch a SLURM job across their cluster. I think if SLURM support were added, the `BAT.py/BAT/run_files/` folder would need to be organized better like into folders based on portion of calculation or job scheduler. It's getting a little crowded in there. I'd like to have some SLURM scripts for running BAT.py on the `cluster2.mccammon.ucsd.edu`, but since that cluster has some special SLURM quirks I thought it might be a better use of time to write general SLURM scripts, share them either in the repo or in the comments here, and then adapt them for my personal needs later.

Anyway, is this a good idea? Is it a useful and straightforward addition? Let me know.

**Comment by GHeinzelmann** [comment]
Hi Jake, thanks for the suggestions. The run_files folder could indeed be more organized, especially since these templates should be edited by the users to their local configuration. Adding general SLURM scripts would also be interesting, do you have a way to test them beforehand? Like a server or local machine that can run the simulations with a general SLURM script?

**Comment by jaketanderson** [comment]
I can test them on `cluster2.mccammon.ucsd.edu`. I'm thinking a bash script with a configurable node list could start SLURM jobs, doing either one pose per node or one section (equil, fe, rest) per pose per node. `cluster2` has eight four-GPU nodes, so each SLURM worker will need to be using as many GPUs as available, which is just a quick change in the run files.

**Comment by GHeinzelmann** [comment]
Cool, let me know how it goes, then we can see about adding these SLURM scripts to the code. I will close this Issue now, perhaps we can discuss it further over email? You can send me an email to the address in the program in the main page and I'll get back to you ASAP. Thanks!
