### ISSUE TITLE
Input files preparation

### ISSUE THREAD

**Issue by quantaosun** [GHeinzelmann/BAT.py#29]
Hi, 
I previously always used Schrodinger's Maestro as docking engine. Do we have to use Autodock workflow to prepare input files for  BAT.py ? If not, how should I modify the files I obtained from other docking engines?

If only Autodock is supported,  then I must install all 3 or 4 more packages, like chimera and Mgltools etc. Could anyone possibly share the detailed way to install those packages? I have tried but failed due to the python version being incompatible etc (The link attached in BAT.py readme, which introduces how to use CELPPade seems to have some out-of-date link there, I can't repeat that workflow). I know it sounds simple, but we all understand it is those little bugs that stop us most of the time. 

In return, I might be able to share a complete Colab version of BAT, from beginning to end, using Google's free GPU, to allow those who do not have access to a computer cluster or supercomputer, can also run BAT.py. But help me first, please!

Cheers

Q

**Comment by GHeinzelmann** [comment]
Hello, and thanks for your interest in the BAT program! Yes, you can definitely use files from other docking programs as input to the BAT workflow. In a recent publication using BAT (https://www.nature.com/articles/s41598-022-17480-w), Mudong Feng did the docking part using Schrodinger's Maestro, and the input files worked fine. If he made any adjustments in the code they were very minor.

So you would have to make a few tests with your docked files, and I can help you with that until we make it work. For now I can give you some general guidelines.

- You need one VMD-readable pdb coordinate file with the docked receptor only, which would be the LMCSS-5uf0_5uez_docked.pdb file from the tutorial. 

- You will also need files for each of the docked poses, also in pdb format readable by VMD, named as in the tutorial (pose0.pdb, pose1.pdb, etc.) 

- All the input files above should be included in the all-poses folder. Remember that you still have to set up a few things for a new protein system, such as the reference.pdb file, the protein anchors, search range, etc., as explained in the User Guide.

- You can choose to keep the protons from the docked ligand file or have BAT reprotonate the molecule using babel, using yes or no for the retain_lig_prot variable in the BAT input file. I would suggest keeping the Maestro protonation (retain_lig_prot = yes).

That should work, but let me know if anything comes up so we can address it. The google free GPU idea sounds great, I would very much like to add that to the code, thanks for the help.

Germano

**Comment by quantaosun** [comment]
Thanks for replying

I have figured out to use Autodock workflow. The Jupyter notebook for colab is under development, will share after some test.

Cheers,

Q

**Comment by GHeinzelmann** [comment]
Cool, but it is still probably better to use Maestro if you have access to it. Hopefully the free GPU idea works too, let me know if you have any questions, you can contact me directly by email then.

Thanks again. Closing issue.
