### ISSUE TITLE
Calculating absolute binding free energy for membrane protein - ligand complex system

### ISSUE THREAD

**Issue by MihyunSeo** [GHeinzelmann/BAT.py#33]
Hello :)

I really appreciate your program, and I've found it very useful.

I'm attempting to create my own system with a membrane protein-ligand complex for absolute binding free energy calculation.
Is BAT.py supporting a calculation for a lipid membrane-including system?

**Comment by GHeinzelmann** [comment]
Hello. In principle yes, if you consider the membrane lipid molecules as cobinders and follow the BAT instructions on how to add them it should work. But I have never tested it, and I am very interested in doing so, so let me know how that goes, and I can help as well.

**Comment by MihyunSeo** [comment]
Hello again!
I tried running a simulation following your instruction, with "other_mols  = [PA,PC,OL]"  in input-dd-amber.in file.

But I've got an error that says:

Traceback (most recent call last):
    File "BAT.py", line 670, in <module>
        build.create_box(comp, hmr, pose, mol, num_waters, water_model, ion_def, neut, buffer_x, buffer_y, buffer_z, stage, ntpr, ntwr, ntwe, ntwx, cut, gamma_ln, barostat, receptor_ff, ligand_ff, dt, dec_method, other_mol, solv_shell)
    File "/home/usr/BAT.py/BAT/lib/build.py", line 1125, in create_box
        box_volume = scripts.box_volume()
    File "/home/use/BAT.py/BAT/lib/scripts.py", line 85, in box_volume
        box_volume=float(ratio * x_axis * y_axis * z_axis)
UnboundLocalError: local variable 'ratio' referenced before assignment


So I checked the equil/pose0/tmp.log file and it says:

$AMBERHOME/bin/teLeap: Fatal Error!
Could not open file pa.frcmod: not found
Exiting LEaP: Errors = 1; Warnings = 0; Notes = 0.


I suspect this is a problem related to force field compatibility. Should I use other force fields that support lipid atoms?
Or is it due to other problems?

**Comment by GHeinzelmann** [comment]
Hello. Did you add the parameters for the lipid molecules inside the build_files folders (see section 7.4 of the user guide)? Or are they included in the Ambertools parameter library? If the latter is the case, we can also make it work with some adjustments.

**Comment by GHeinzelmann** [comment]
Will try membrane proteins in the future.
