### ISSUE TITLE
Necessary requirements for usage

### ISSUE THREAD

**Issue by GattiMh** [GHeinzelmann/BAT.py#35]
Hello,

thanks for uploading the tool.
I haven't tested it yet but I was wondering if it is required to have VMD and LovoAlign installed or if it accessory.
The same would be for Amber since you have implemented openmm, would it require to have AmberTools installed?

Many thanks

**Comment by GHeinzelmann** [comment]
Hi, yes all of them have to be installed, except the pmemd.cuda simulation engine from Amber if you are using OpenMM.

**Comment by GattiMh** [comment]
Thanks for the reply.

I was wondering if it is possible to use another software instead of VMD because it would require a license for commercial usage. Haven't check the license for LovoAlign.

Best

**Comment by GHeinzelmann** [comment]
Hello. VMD is needed for a series of coordinate transformations and atom selections that use tcl scripting. If there is a program with the same tcl funcionality it could be used too I suppose, but I haven’t looked for that. If you find it I would be happy to know about it too.

About lovoalign, you can get some information on their page or contact the authors.

**Comment by GHeinzelmann** [comment]
Seems solved, closing issue.
